export enum Text {
  ASSUNTOS_DO_MOMENTO = 'assuntos do momento',
  CARREGANDO = 'Carregando...',
  DISCLAIMER_1 = 'O resultados apresentados pela plataforma são baseados em dados reais capturados do Twitter e não refletem as nossas opiniões.',
  DISCLAIMER_2 = 'Não nos responsabilizamos por qualquer conteúdo ofensivo.',
  EMPATWI_2021 = '© Empatwi 2021',
  O_QUE_ESTAO_PENSANDO_SOBRE = 'O que estão pensando sobre...?',
  QUANTIDADE = 'Quantidade',
  RESULTADOS_DA_BUSCA_POR = 'resultados da busca por',
  TOTAL = 'Total',
  TWEETS = 'Tweets',
  TWEETS_ANALISADOS = 'tweets analisados',
  TWEETS_NEGATIVOS = 'tweets negativos',
  TWEETS_POSITIVOS = 'tweets positivos',
}
